server:
  port: 10011
  servlet:
    context-path: /upload

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 50MB # 限制文件上传的大小
      max-request-size: 50MB
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 47.95.234.255:22122
weekend:
  upload:
    baseUrl: http://47.95.234.255/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp